import type { Effect } from './types';

export const EFFECTS: Effect[] = [
  {
    id: 'vintage',
    name: '复古风格',
    description: '旧时光的温暖色调',
    prompt: 'Apply a vintage photo effect with a warm, sepia tone, slightly faded colors, and subtle grain. Make it look like an old, classic photograph from the 1970s.',
  },
  {
    id: 'b&w',
    name: '黑白经典',
    description: '高对比度的艺术感',
    prompt: 'Convert this photo to a high-contrast black and white image. Emphasize the light and shadows to create a dramatic, artistic effect.',
  },
  {
    id: 'portrait',
    name: '人像模式',
    description: '主体锐化，背景虚化',
    prompt: 'Apply a portrait mode effect. Sharpen the main subject and apply a subtle, natural-looking blur to the background to create depth of field.'
  },
  {
    id: 'golden-hour',
    name: '黄金时刻',
    description: '梦幻般的温暖光线',
    prompt: 'Apply a golden hour effect. Bathe the image in a soft, warm, glowing light, enhance the warm tones like yellows and oranges, and create long, soft shadows for a dreamy and magical atmosphere.',
  },
  {
    id: 'cinematic-teal-orange',
    name: '电影色调',
    description: '青色与橙色的碰撞',
    prompt: 'Apply a cinematic teal and orange color grade. Shift the highlights and midtones towards teal and cyan, while pushing the shadows and skin tones towards warm orange and red. Increase the overall contrast for a modern, blockbuster movie look.',
  },
  {
    id: 'long-exposure',
    name: '长曝光',
    description: '丝滑水流与光轨',
    prompt: "Simulate a long exposure effect. If there is moving water, make it look silky and smooth. If it's a night scene with lights, create motion blur and light trails from moving objects. Keep stationary objects sharp.",
  },
  {
    id: 'lomo',
    name: 'LOMO相机',
    description: '高饱和度与暗角',
    prompt: 'Create a Lomo effect. Drastically increase color saturation and contrast, add a heavy, dark vignette around the edges, and introduce a slight color shift to give it a toy camera, cross-processed film look.',
  },
  {
    id: 'pop-art',
    name: '波普艺术',
    description: '安迪·沃霍尔风格',
    prompt: "Transform this photo into a vibrant, colorful pop art style, similar to Andy Warhol's work. Use bold, contrasting colors, and a screen-printed look.",
  },
  {
    id: 'watercolor',
    name: '水彩画',
    description: '轻盈通透的笔触',
    prompt: 'Make this photo look like a watercolor painting. Use soft, blended colors, visible brush strokes, and a textured paper background.',
  },
  {
    id: 'sketch',
    name: '铅笔素描',
    description: '细腻的线条描绘',
    prompt: 'Convert this photo into a detailed pencil sketch. It should look hand-drawn, with clear outlines, shading, and cross-hatching for texture.',
  },
  {
    id: 'manga',
    name: '漫画风格',
    description: '日式黑白漫画感',
    prompt: "Transform this photo into a dramatic Japanese manga style. Use high-contrast black and white, apply screentone patterns for shading and texture, and emphasize dynamic action lines. The result should look like a page from a professionally drawn manga.",
  },
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    description: '霓虹灯下的未来都市',
    prompt: "Dramatically transform this photo into an intense, futuristic cyberpunk cityscape. Saturate the scene with vibrant, glowing neon lights, focusing on electric blues, hot pinks, and acid greens. Plunge the shadows into deep, inky blacks to create extreme contrast. Add elements like holographic advertisements, rainy, reflective streets, and a dense, moody atmosphere. The final image should feel like a still from a high-budget sci-fi blockbuster film.",
  },
  {
    id: 'eye-of-cosmos',
    name: '星辰之眼',
    description: '史诗级星空增强',
    prompt: "Transform the sky in this photo into an epic and crystal-clear celestial masterpiece. Your primary goal is absolute sharpness and clarity. 1. **Stars**: Render all stars as tack-sharp, brilliantly clear points of light. There should be zero blur or smudging. The sky should be filled with a mix of fine, distant stars and a few brighter, more prominent ones that have a subtle, crisp glow. 2. **Milky Way**: The centerpiece should be a stunningly detailed Milky Way galaxy. Be creative with its composition: it could be a majestic vertical pillar of light, a grand horizontal arc stretching across the horizon, or a dynamic diagonal slash. The Milky Way must show intricate detail, with dark dust lanes contrasting against glowing nebulae and dense star fields. 3. **Details**: To enhance the realism and sense of wonder, you may subtly add a small, distant star cluster if it complements the scene. 4. **Overall Mood**: The final image should be awe-inspiring, with a deep, dark sky that makes the celestial objects pop with incredible vibrancy and clarity. It should look like a professional astrophotograph taken under perfect conditions.",
  },
  {
    id: 'star-trails',
    name: '星轨之舞',
    description: '捕捉地球的旋转',
    prompt: "Simulate a long-exposure star trail photograph. Transform the stars in the sky into mesmerizing circular light trails, as if capturing the Earth's rotation over a long period. Keep the foreground landscape and any stationary objects sharp and clear.",
  },
  {
    id: 'aurora-dream',
    name: '梦幻极光',
    description: '为夜空增添绚丽光彩',
    prompt: 'Add a beautiful, ethereal aurora borealis (northern lights) effect to the sky in this photo. The aurora should have flowing ribbons of green and magenta light, look natural within the scene, and reflect realistically on any water or landscape elements present.',
  },
  {
    id: 'glitch',
    name: '故障艺术',
    description: '充满未来感的数字干扰',
    prompt: 'Transform this photo with a glitch art effect. Introduce digital artifacts like RGB color splitting, pixel sorting, datamoshing, and scan lines. The effect should be stylish and intentional, creating a futuristic, deconstructed aesthetic without making the original subject completely unrecognizable.',
  },
  {
    id: 'neon-sketch',
    name: '霓虹素描',
    description: '发光的定制霓虹招牌',
    prompt: 'Convert the main subject of this photo into a glowing neon sketch. Trace the key outlines of the subject with bright, vibrant neon lines (e.g., pink, blue, cyan). Place the neon sketch against a dark, moody background like a brick wall or a dark cityscape to make the glow pop. The final image should look like a custom neon sign.',
  },
  {
    id: 'light-painting',
    name: '动态光绘',
    description: '用光在空中作画',
    prompt: 'Add a dynamic light painting effect to this image. Weave vibrant, flowing trails of light around the main subject or through the scene. The light trails should look like they were created with a long-exposure photograph, adding a sense of motion and energy. Use a variety of colors for the light trails to create a visually stunning and magical effect.',
  },
  {
    id: 'intelligent-merge',
    name: '智能场景融合',
    description: 'AI分析并逻辑性地合成新照片',
    prompt: 'You are an expert photo editor. Analyze the content of all provided images. Your task is to create a single, new, photorealistic photograph that logically and seamlessly merges the subjects and environments from all images. Do not create a collage or a simple blend. Instead, intelligently integrate the elements into a single, coherent scene, ensuring consistent lighting, shadows, and perspective. For example, if given an image of a person and an image of a landmark, place the person realistically in front of the landmark. The final output must be one believable photo.',
    multiImage: true,
  },
  {
    id: 'seamless-blend',
    name: '艺术化融合',
    description: '超现实双重曝光',
    prompt: 'Create a seamless, artistic double exposure effect by blending the provided images into a single, cohesive work of art. Intelligently merge the key elements from each photo, such as blending a portrait with a landscape, or combining two scenes into a surreal, dreamlike image. The final result should be a single, beautiful image where the boundaries between the original photos are invisible and artistically integrated.',
    multiImage: true,
  },
  {
    id: 'scrapbook-collage',
    name: '手帐风拼贴',
    description: '宝丽来与和纸胶带',
    prompt: "Create a charming digital scrapbook page from the provided images. Transform each image into a slightly tilted Polaroid-style print with a white border. Arrange them in a casual, overlapping layout. Add subtle, realistic details like small pieces of washi tape holding the corners of some photos. The background should be a simple, textured paper look.",
    multiImage: true,
  },
  {
    id: 'photo-booth-strip',
    name: '复古大头贴',
    description: '经典的竖向连拍',
    prompt: "Arrange the provided images sequentially in a vertical photo booth strip format. Each image should occupy its own frame within the strip. Give the strip a classic, high-contrast look, either in black and white or with slightly faded, vintage colors. The final output must be a single, tall, vertical image that looks like a real photo booth print.",
    multiImage: true,
  },
];